language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t bumeranghc/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true bumeranghc/docker-react npm run test

deploy:
    provider: elastikbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-618738725193"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
